version: '3.9'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:12009
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:12009:12009"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    restart: always