# Generated by Django 4.2.3 on 2023-07-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('transactionhash', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserOperationHash',
            fields=[
                ('userophash', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('transactionhash', models.CharField(max_length=255)),
            ],
        ),
    ]
