# Generated by Django 4.2.3 on 2023-07-14 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transactionstatus',
            table='txn_status',
        ),
        migrations.AlterModelTable(
            name='useroperationhash',
            table='userop_txn',
        ),
    ]
